# Global settings
default-lease-time 3600;
max-lease-time 7200;
authoritative;

# Subnet declaration
subnet 192.168.42.0 netmask 255.255.255.0 {
  range 192.168.42.63 192.168.42.163;
  option routers 192.168.42.1;
  option subnet-mask 255.255.255.0;
  option domain-name-servers 8.8.8.8, 8.8.4.4;
  option domain-name "lab.local";
}

host reserved-client {
 hardware ethernet 52:54:00:62:7c:3b;
 fixed-address 192.168.42.204;
}

